<a href="https://colab.research.google.com/github/Anibas23/Data-Science/blob/main/third.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1=[1,3.5,6,9,7] #LIST
arr1= np.array(data1)#array1


In [3]:
data1

[1, 3.5, 6, 9, 7]

In [4]:
arr1

array([1. , 3.5, 6. , 9. , 7. ])

In [5]:
data2=[2,8,5,9,3] #tuple
arr2= np.array(data2)

In [6]:
data2

[2, 8, 5, 9, 3]

In [7]:
arr2

array([2, 8, 5, 9, 3])

In [8]:
arr1.ndim #array1 o'lchami

1

In [9]:
arr2.ndim #array2 o'lchami

1

In [11]:
data3= [[3,5,9,7],[8,2,4,0]] #list ichidagi list (nested list)
arr3= np.array(data3) #array3

In [12]:
data3

[[3, 5, 9, 7], [8, 2, 4, 0]]

In [13]:
arr3

array([[3, 5, 9, 7],
       [8, 2, 4, 0]])

In [15]:
arr3.ndim #arr3 ning o'lchami

2

In [16]:
data4 = [[1,3,5,7,9],[2,4,6,8,0],[1,2,3,4,5]] #data3 (nestedlist)
arr4=np.array(data4) #arr4 (nestedlist)

In [17]:
data4

[[1, 3, 5, 7, 9], [2, 4, 6, 8, 0], [1, 2, 3, 4, 5]]

In [18]:
arr4

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0],
       [1, 2, 3, 4, 5]])

In [19]:
arr4.ndim #arr4 o'lchami

2

In [21]:
arr4.shape #qator va ustunlar soni (q,u)

(3, 5)

In [22]:
arr4.size #

15

In [25]:
arr4= np.zeros(shape=(3,5)) #barcha elementlar 0 ga teng (3,5) o'lchamli massiv
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
arr4= np.ones(shape=(3,5)) #barcha elementlar 1 ga teng (3,5) o'lchamli massiv
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr5=np.arange(2, 32, 2) #2dan 32 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi 
arr5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [28]:
arr6=np.arange(30) # 0 dan 30 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])